name: Auto Assign

on:
    issues:
        types: [ opened ]
    pull_request_target:
        types: [opened, reopened]

permissions:
    issues: write
    pull-requests: write

jobs:
    assign:
        runs-on: ubuntu-latest
        steps:
            - name: Auto-assign
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: 'NeakTolaDev'
