name: Proof HTML
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./
